/run/verbose 1
/tracking/verbose 0
#/gps/particle geantino
/gps/particle geantino
/gps/pos/type Beam
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/pos/shape Circle
/gps/pos/centre -1.50 0 0 m
/gps/pos/radius 0.305 mm
#/gps/pos/sigma_r
/gps/ang/type beam1d
/gps/ang/rot1 0 0 1
/gps/ang/rot2 0 1 0
/gps/ang/sigma_r 0.5 mrad
/gps/ene/type Gauss
/gps/ene/mono 100 MeV
/gps/ene/sigma 0.7 MeV
/run/beamOn 10
